#!/bin/bash
set -e
TMP=$(mktemp -d)
BUNDLE=bundle
BUNDLE_TAR=${BUNDLE}.tar.gz
cd ${TMP}
wget $(curl https://api.github.com/repos/g4s8/.dotfiles/releases/latest | grep tarball | cut -d\" -f4) -O${BUNDLE_TAR}
tar xvzf $BUNDLE_TAR
cd $BUNDLE
make all
cd /tmp
rm -fr ${TMP}
